<option value="apartamento">Apartamento</option>
<option value="apartamentoamueblado">Apartamento amueblado</option>
<option value="bodega">Bodega</option>
<option value="casa">Casa</option>
<option value="casa2pisos">Casa de 2 pisos</option>
<option value="casa de playa">Casa de playa</option>
<option value="condominio">Condominio</option>
<option value="habitacion">Habitacion</option>                
<option value="edificiocomercial">Edificio comercial</option> 
<option value="edificiohabitacional">Edificio habitacional</option> 
<option value="finca/hacienda">Finca/hacienda</option>
<option value="hotel">Hotel</option>
<option value="isla">Isla</option>              
<option value="lote">Lotes</option>
<option value="terreno">Terrenos</option>
<option value="local comercial">Local comercial</option>
<option value="local de oficina">Local para oficina</option>                
<option value="naves industriales">Naves industriales</option>