<!-- <option value="argentina">Argentina</option> 
<option value="bolivia">Bolivia</option>
<option value="brasil">Brasil</option>
<option value="chile">Chile</option>
<option value="colombia">Colombia</option>
<option value="costa rica">Costa Rica</option>
<option value="cuba">Cuba</option>
<option value="ecuador">Ecuador</option>
<option value="el salvador">El Salvador</option>
<option value="espana">España</option>
<option value="guatemala">Guatemala</option>
<option value="honduras">Honduras</option>
<option value="mexico">Mexico</option> -->
<option value="nicaragua">Nicaragua</option>
<!-- <option value="panama">Panamá</option>
<option value="paraguay">Paraguay</option>
<option value="peru">Perú</option>
<option value="republica dominicana">República Dominicana</option>
<option value="uruguay">Uruguay</option>
<option value="venezuela">Venezuela</option> -->